{{ $ingress := (lookup "networking.k8s.io/v1" "Ingress" .Release.Namespace "sync") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sync
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ if $ingress }}
    {{ toYaml $ingress.metadata.annotations | nindent 4 }}
    {{ else }}
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '6000'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '6000'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '6000'
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: '6000'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    {{ end }}
spec:
  {{ if $ingress }}
  {{ toYaml $ingress.spec | nindent 2 }}
  {{ else }}
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /sync/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: sync
            port:
               number: 4000
  {{ end }}