apiVersion: v1
kind: Service
metadata:
   name: sync
   namespace: {{ .Release.Namespace }}
spec:
   type: ClusterIP
   selector:
      app: sync
   ports:
      - port: 4000
        targetPort: 4000
