{{ $secret := (lookup "v1" "Secret" .Release.Namespace "mongodb") }}
{{ $sts := (lookup "apps/v1" "StatefulSet" .Release.Namespace "mongodb") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: "mongo-admin"
  {{ if $secret }}
  password: {{ $secret.data.password | b64dec }}
  keyfile: {{ $secret.data.keyfile | b64dec }}
  {{ else }}
  password: {{ derivePassword 1 "long" .Release.Name .Chart.Name uuidv4 | b64enc | trimSuffix "=" | quote }}
  keyfile: {{ include "randAlphaNumBase64Safe" 756 | b64enc | trimSuffix "=" | quote }}
  {{ end }}
  databaseURI: "mongodb://mongodb.{{ .Release.Namespace }}/agnost?retryWrites=true&w=majority&authSource=admin"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb
  namespace: {{ .Release.Namespace }}
data:
  mongod.conf: |
    storage:
      dbPath: /data/db
    net:
      bindIp: 0.0.0.0
    replication:
      replSetName: rs0
    security:
      authorization: enabled
      keyFile: /etc/mongodb-keyfile/keyfile.txt
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init
  namespace: {{ .Release.Namespace }}
data:
  mongod.conf: |
    storage:
      dbPath: /data/db
    net:
      bindIp: 0.0.0.0
    replication:
      replSetName: rs0
      
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: mongodb
  {{- if not .Release.IsUpgrade }}
  replicas: 1
  {{- else }}
  replicas: {{ $sts.spec.replicas }}
  {{- end }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      partition: 0
  revisionHistoryLimit: 10
  podManagementPolicy: OrderedReady
  persistentVolumeClaimRetentionPolicy: 
    whenDeleted: Retain
    whenScaled: Retain
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: docker.io/mongo:7.0.7
        command:
        - mongod
        - "--config"
        - "/config/mongod.conf"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
          name: mongod
        resources:
        {{- if not .Release.IsUpgrade }}
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 1Gi
            cpu: 1
        {{- else }}
          {{ (index $sts.spec.template.spec.containers 0).resources | toYaml | indent 10 | trim }}
        {{- end }}
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: password
        livenessProbe:
          tcpSocket:
            port: 27017
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 6
        readinessProbe:
          tcpSocket:
            port: 27017
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 6
        volumeMounts:
        - name: config
          mountPath: /config
        - name: data
          mountPath: /data/db
        - name: keyfile
          mountPath: /etc/secrets
          readOnly: true
        - name: keyfile-copy
          mountPath: /etc/mongodb-keyfile
      initContainers:
      - name: init
        image: docker.io/mongo:7.0.7
        command:
        - bash
        - -c
        - >
          cp /etc/secrets/keyfile.txt /etc/mongodb-keyfile/keyfile.txt &&
          chmod 600 /etc/mongodb-keyfile/keyfile.txt &&
          echo "Starting MongoDB..." &&
          mongod --config /config/mongod.conf --fork --logpath /var/log/mongod.log --dbpath /data/db &&
          echo "Started MongoDB..." &&
          sleep 5 &&
          RS_STATUS=$(mongosh --quiet --eval "rs.status().ok"); 
          if [[ $RS_STATUS == 1 ]]; then
            echo "MongoDB is already initialized.";
          else
            echo "Initializing MongoDB...";
            mongosh --eval "rs.initiate({_id: 'rs0', members: [{ _id: 0, host: 'mongodb-0.mongodb.{{ .Release.Namespace }}.svc.cluster.local:27017' }]})";
            echo "MongoDB initialized.";
          fi &&
          USER_EXISTS=$(mongosh --eval "db.getSiblingDB('admin').getUser('${MONGO_INITDB_ROOT_USERNAME}')" --quiet) &&
          if [[ $USER_EXISTS != "null" ]]; then
            mongosh --eval "db.getSiblingDB('admin').dropUser('${MONGO_INITDB_ROOT_USERNAME}')";
          fi &&
          echo "Creating user..." &&
          mongosh --eval "db.getSiblingDB('admin').createUser({user: '${MONGO_INITDB_ROOT_USERNAME}', pwd: '${MONGO_INITDB_ROOT_PASSWORD}', roles: [{role: 'root', db: 'admin'}]})" &&
          echo "Shutting down..." &&
          mongod --shutdown
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: password
        volumeMounts:
        - name: config-init
          mountPath: /config
        - name: data
          mountPath: /data/db
        - name: keyfile
          mountPath: /etc/secrets
        - name: keyfile-copy
          mountPath: /etc/mongodb-keyfile
      volumes:
      - name: config
        configMap:
          name: mongodb
      - name: config-init
        configMap:
          name: mongodb-init
      - name: keyfile
        secret:
          secretName: mongodb
          items:
          - key: keyfile
            path: keyfile.txt
      - name: keyfile-copy
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          {{- if not .Release.IsUpgrade }}
          storage: 1Gi
          {{- else }}
          storage: {{ (index $sts.spec.volumeClaimTemplates 0).spec.resources.requests.storage }}
          {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 27017
    targetPort: 27017
    name: mongodb
  clusterIP: None
  selector:
    app: mongodb

