{{- if index .Values "cert-manager" "enabled" }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ index .Values "cert-manager" "namespace" }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
{{- end }}
