{{ $secret := (lookup "v1" "Secret" .Values.base.namespaceOverride "redis") }}
apiVersion: v1
kind: Secret
metadata:
  name: redis
  namespace: {{ .Values.base.namespaceOverride }}
type: Opaque
stringData:
  {{ if $secret }}
  password: {{ $secret.data.password | b64dec }}
  {{ else }}
  password: {{ derivePassword 1 "long" .Release.Name .Chart.Name uuidv4 | b64enc | trimSuffix "=" | quote }}
  {{ end }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
  namespace: {{ .Values.base.namespaceOverride }}
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode yes
    port 6379
    requirepass ${REDIS_PASSWORD}
    dir /data
    appendonly yes

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: {{ .Values.base.namespaceOverride }}
spec:
  serviceName: redis
  replicas: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      partition: 0
  revisionHistoryLimit: 10
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image:  docker.io/redis:7.2.5
        command: ["redis-server", "/redis-master/redis.conf"]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
          name: redis
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: password
        livenessProbe:
          exec:
            command:
            - redis-cli
            - -a
            - $(REDIS_PASSWORD)
            - ping
          failureThreshold: 5
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 6
        readinessProbe:
          exec:
            command:
            - redis-cli
            - -a
            - $(REDIS_PASSWORD)
            - ping
          failureThreshold: 5
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 2
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /redis-master
      volumes:
      - name: config
        configMap:
          name: redis
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 512Mi

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.base.namespaceOverride }}
spec:
  ports:
  - port: 6379
    name: redis
  clusterIP: None
  selector:
    app: redis
