{{ $secret := (lookup "v1" "Secret" .Release.Namespace "agnost") }}
apiVersion: v1
kind: Secret
metadata:
  name: agnost
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
stringData:
  {{ if $secret -}}
  clusterAccessToken: {{ $secret.data.clusterAccessToken | b64dec }}
  masterToken: {{ $secret.data.masterToken | b64dec }}
  passPhrase: {{ $secret.data.passPhrase | b64dec }}
  clusterSlug: {{ $secret.data.clusterSlug | b64dec }}
  {{ else -}}
  clusterAccessToken: {{ (printf "at-%s" (derivePassword 1 "maximum" .Release.Name .Chart.Name uuidv4 | b64enc | trimSuffix "=" | lower)) }}
  masterToken: {{ (printf "mt-%s" (derivePassword 1 "maximum" .Release.Name .Chart.Name uuidv4 | b64enc | trimSuffix "=" | lower)) }}
  passPhrase: {{ derivePassword 1 "maximum" .Release.Name .Chart.Name uuidv4 | b64enc | trimSuffix "=" | lower | quote }}
  clusterSlug: {{ include "slugAlphaNumBase64Safe" 8 | quote }}
  {{ end -}}

