apiVersion: v2
name: base
description: Agnost GitOps Platform Installation
version: 1.0.3
appVersion: "v1.0.2"
dependencies:
- name: ingress-nginx
  version: "4.8.4"
  repository: "file://../ingress-nginx"
  condition: ingress-nginx.enabled
- name: cert-manager
  version: "1.14.5"
  repository: https://charts.jetstack.io
  condition: cert-manager.enabled
- name: agnost-webhook
  version: "1.0.0"
  repository: "file://../webhook"
