apiVersion: v2
name: base
description: Agnost GitOps Platform Installation
version: 0.1.8
appVersion: "v0.0.31"
dependencies:
- name: ingress-nginx
  version: "4.10.1"
  repository: https://kubernetes.github.io/ingress-nginx
  condition: ingress-nginx.enabled
- name: cert-manager
  version: "1.14.5"
  repository: https://charts.jetstack.io
  condition: cert-manager.enabled
- name: agnost-webhook
  version: "1.0.0"
  repository: "file://../webhook"
