ingress-nginx:
  # Install ingress-nginx
  enabled: true
  # Namespace for ingress-nginx
  namespaceOverride: "ingress-nginx"
  controller:
    autoscaling:
      # Enable/Disable autoscaling for ingress-nginx
      enabled: true
      # Minimum ingress-nginx replicas when autoscaling is enabled
      minReplicas: 1
      # Maximum ingress-nginx replicas when autoscaling is enabled
      maxReplicas: 5
      # Target CPU Utilization for ingress-nginx replicas when autoscaling is enabled
      targetCPUUtilizationPercentage: 80
      # Target Memory Utilization for ingress-nginx replicas when autoscaling is enabled
      targetMemoryUtilizationPercentage: 80

cert-manager:
  # Install cert-manager
  enabled: true
  # Namespace for cert-manager
  namespace: "cert-manager"
  startupapicheck:
    # No need for pre checks
    enabled: false

base: 
  namespaceOverride: "agnost"
