{{ $dply := (lookup "apps/v1" "Deployment" .Release.Namespace "studio") }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: studio
  namespace: {{ .Release.Namespace }}
  labels:
    app: studio
spec:
  {{- if not .Release.IsUpgrade }}
  replicas: 1
  {{- else }}
  replicas: {{ $dply.spec.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: studio
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: studio
    spec:
      initContainers:
      - name: wait-for-platform-core
        image: curlimages/curl:8.1.1
        imagePullPolicy: IfNotPresent
        args: [ 'sh', '-c', 'until [[ "$(curl -s http://platform.{{ .Release.Namespace }}.svc:4000/ping)" == *"Pong!" ]]; do echo "Sleeping a bit..."; sleep 3; done; echo "platform is ready!";' ]
      containers:
      - name: studio
        image: {{ .Values.studio.image }}:{{ .Values.studio.tag }}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 4000
        env:
          - name: NAMESPACE
            value: {{ .Release.Namespace }}
          - name: RELEASE_NUMBER
            value: {{ .Chart.AppVersion }}
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 6
        startupProbe:
          httpGet:
            path: /health
            port: 4000
          failureThreshold: 30
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 6
        resources:
        {{- if not .Release.IsUpgrade }}
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 500m
        {{- else }}
          {{ (index $dply.spec.template.spec.containers 0).resources | toYaml | indent 10 | trim }}
        {{- end }}
