apiVersion: v1
kind: Service
metadata:
   name: studio
   namespace: {{ .Release.Namespace }}
spec:
   type: ClusterIP
   selector:
      app: studio
   ports:
      - port: 4000
        targetPort: 4000
