name: Build and Deploy

on:
  push:
    branches:
      - 'main'
    paths:
      - 'base/Chart.yaml'

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Charts
        uses: actions/checkout@v3
        with:
          ref: main
          path: charts
      -
        name: Checkout Pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: pages
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      -
        name: Package Helm Charts
        run: |
          sudo dpkg -i https://github.com/norwoodj/helm-docs/releases/download/v1.13.1/helm-docs_1.13.1_Linux_x86_64.rpm
          cd ./charts
          mkdir chart-files
          helm-docs -g base  --ignore-non-descriptions --sort-values-order file
          helm package --dependency-update base
          mv base-*.tgz  ../pages/
          helm repo index ../pages/ --url https://cloud-agnost.github.io/agnost-gitops-charts/
          cp base/README.md ../repos/
          cp base/README.md .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "README update"
          git push
      -
        name: Publish on Pages
        run: |
          cd ./pages
          git add .
          git commit -m "New release"
          git push
